# Generated by Django 3.2.5 on 2021-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('team_symbol', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
