# Generated by Django 3.2.5 on 2021-07-01 18:39

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('index', models.IntegerField()),
                ('event_type', models.IntegerField(choices=[(1, 'CREATE_SYSTEM'), (2, 'CREATE_USER'), (3, 'UPDATE_SYSTEM'), (4, 'UPDATE_USER'), (5, 'DELETE_SYSTEM'), (6, 'DELETE_USER')], default=stats.models.EventTypes['CREATE_SYSTEM'])),
                ('event', jsonfield.fields.JSONField()),
            ],
            options={
                'unique_together': {('uid', 'index')},
            },
        ),
        migrations.CreateModel(
            name='StatsProjection',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('att_g', models.FloatField()),
                ('att', models.IntegerField()),
                ('yds', models.FloatField()),
                ('avg', models.FloatField()),
                ('yds_g', models.FloatField()),
                ('td', models.IntegerField()),
                ('lng', models.CharField(max_length=3)),
                ('first_down', models.IntegerField()),
                ('first_down_pct', models.FloatField()),
                ('yard_20_p', models.IntegerField()),
                ('yard_40_p', models.IntegerField()),
                ('fum', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'unique_together': {('uid', 'index')},
            },
        ),
    ]
